spring:
  application:
    name: chat
  ai:
    google:
      genai:
        api-key: ${GEMINI_API_KEY}
        chat:
          model: gemini-flash-latest
server:
  port: 8082

logging:
  level:
    root: info