version: '3.8'

services:
  activemq:
    image: apache/activemq-classic:6.1.4
    container_name: activemq
    ports:
      - "61616:61616"
      - "8161:8161"
    volumes:
      - ./activemq.xml:/opt/apache-activemq/conf/activemq.xml
    environment:
      - ACTIVEMQ_ADMIN_LOGIN=admin
      - ACTIVEMQ_ADMIN_PASSWORD=admin
      - ACTIVEMQ_MIN_MEMORY=512
      - ACTIVEMQ_MAX_MEMORY=2048
